# Generated by Django 2.2.3 on 2019-07-05 18:34

import datetime
from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'})),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 20, 34, 40, 381168))),
            ],
        ),
    ]
