# Generated by Django 2.2.3 on 2019-07-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
