# Generated by Django 2.2.3 on 2019-07-05 13:51

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('live_demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}),
        ),
    ]
