# Generated by Django 2.2.3 on 2019-07-08 10:02

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('live_demo', '0002_auto_20190705_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=mapbox_location_field.models.AddressAutoHiddenField(default='created before implemented reverse geocoding'),
            preserve_default=False,
        ),
    ]
