# Generated by Django 2.2.3 on 2019-07-05 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_demo', '0002_auto_20190705_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 15, 58, 30, 759469)),
        ),
    ]
