# Generated by Django 2.2.7 on 2019-11-08 22:06

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('live_demo', '0003_place_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (17.031645, 51.106715), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}),
        ),
    ]
